name: Feature request
description: Suggest an improvement for FlowK
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: How should FlowK behave?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
